import { ProjectDescriptor } from "@/types";

export const projects: ProjectDescriptor[] = [
  {
    src: "/assets/gumroad-cover.png",
    href: "/gumroad",
    name: "Gumroad",
    role: "Product Design",
    alt: "Gumroad logo",
    tag: ["product"],
  },
  {
    src: "/assets/daylight-cover.png",
    href: "/calquo",
    name: "Daylight calculator",
    role: "Product Design",
    alt: "A screenshot of the daylight calculator app",
    tag: ["product"],
  },
  {
    src: "/assets/buidlguidl-cover.png",
    href: "/buidlguidl",
    name: "BuidlGuidl Ethereum",
    role: "Web Design",
    alt: "Buidlguidl logo",
    tag: ["uxui"],
  },
  {
    src: "/assets/nectar-cover.png",
    href: "/nectar",
    name: "Nectar",
    role: "Design System",
    alt: "Nectar logo",
    tag: ["design system"],
  },
  {
    src: "/assets/theatremode-cover.png",
    href: "/theatremode",
    name: "Theatre mode",
    role: "Feature Design",
    alt: "",
    tag: ["product"],
  },
  {
    src: "/assets/avatars-cover.png",
    href: "/avatars",
    name: "Avatars",
    role: "Illustration System",
    alt: "Hand drawn illustration of a girl smiling",
    tag: ["illustration", "design system"],
  },
  {
    src: "/assets/lexicon-cover.png",
    href: "/lexicon",
    name: "Lexicon",
    role: "Design System",
    alt: "Lexicon logo",
    tag: ["design system"],
  },
  {
    src: "/assets/inbolt-cover.png",
    href: "/inbolt",
    name: "Inbolt",
    role: "UI Design",
    alt: "A screenshot of the inbolt app dashboard",
    tag: ["uxui"],
  },
  {
    src: "/assets/calquo-cover.png",
    href: "/calquo",
    name: "Calquo",
    role: "Product Design",
    alt: "A screenshot of the calquo app dashboard",
    tag: ["product"],
  },
  {
    src: "/assets/goeat-cover.png",
    href: "/goeat",
    name: "Goeat",
    role: "UX/UI Design",
    alt: "Hand holding a phone with goeat app",
    tag: ["uxui"],
  },
  {
    src: "/assets/whatsapp-cover.png",
    href: "/whatsapp",
    name: "Whatsapp polls",
    role: "Feature Design",
    alt: "Mobile showing whatsapp polls screen",
    tag: ["uxui"],
  },
];
